// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MehmetTalhaSeker/mts-gr/entdb"
	"github.com/MehmetTalhaSeker/mts-gr/ginserver"
	"github.com/MehmetTalhaSeker/mts-gr/metadb"
	"net/http"
)

// Injectors from wire.go:

func BuildServerCompileTime() *http.Server {
	client := entdb.NewClient()
	metaDBMS := metadb.NewMetaDBMS(client)
	server := ginserver.NewServer(client, metaDBMS)
	return server
}
