// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Meta is the predicate function for meta builders.
type Meta func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)
